sudo: required

language: go

go:
  - 1.10.x

python:
  - "2.7"

before_install:
  - openssl aes-256-cbc -K $encrypted_b2a3a07f2f2c_key -iv $encrypted_b2a3a07f2f2c_iv -in .travis/deploy_key.pem.enc -out .travis/deploy_key.pem -d

script: true

install:
  - go get -v github.com/gohugoio/hugo
  - sudo pip install Pygments

after_success:
  - eval "$(ssh-agent -s)"
  - chmod 600 .travis/deploy_key.pem
  - ssh-add .travis/deploy_key.pem
  - mv -fv .travis/ssh_config ~/.ssh/config
  - ./deploy.sh

notifications:
  email:
    recipients:
      - laoshanlung@gmail.com
    on_success: never
    on_failure: always
